baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "pt-br"
title = "William Amorim"
theme = "anatole"
relativeurls = true
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "William Amorim"
author = "William Amorim"
description = "Este é o meu site pessoal"
profilePicture = "images/profile.jpg"
keywords = ["william amorim"]
favicon = "favicons/"
customCss = ["css/custom.css"]
# example ["js/custom.js"]
# customJs = [] 
mainSections = ["blog", "contos", "timeline"]
doNotLoadAnimations = false

## Math settings
[params.math]
enable = true  
use = "mathjax"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/williamorim"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  weight = 100
  identifier = "home"
  url = "/"
  
  [[menu.main]]
  name = "Timeline"
  weight = 200
  identifier = "timeline"
  url = "/timeline/"

  [[menu.main]]
  name = "Blog"
  weight = 300
  identifier = "blog"
  url = "/blog/"
  
  [[menu.main]]
  name = "Contos"
  weight = 400
  identifier = "contos"
  url = "/contos/"
  
  [[menu.main]]
  name = "Profissional"
  weight = 500
  identifier = "profissional"
  url = "/profissional/"

